name: ci-merge
on: 
  push:
    branches:
    - main
jobs:
  scan_project:
    runs-on: ubuntu-latest
    outputs:
      stacks: ${{ steps.publish.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: |
            pulumi/project_config/project-*/Pulumi.*.yaml
      - name: Generate stack list
        id: publish
        uses: actions/github-script@v6
        with:
          script: |
            updated_stacks = `${{steps.changed-files.outputs.added_files}}`
            added_stacks = `${{steps.changed-files.outputs.modified_files}}`

            const updated_stacks_list = updated_stacks.split(" ");
            const added_stacks_list = added_stacks.split(" ");

            const added_and_updated_stacks = updated_stacks_list.concat(added_stacks_list)

            const added_and_updated_stacks_clean = added_and_updated_stacks.filter(element => {
              return element !== '';
            });

            return added_and_updated_stacks_clean

  # Run preview on each of the stacks (This spins up an individual job per stack)
  preview_stack:
    runs-on: ubuntu-latest
    needs:
      - scan_project
    strategy:
      matrix:
        stacks: ${{ fromJSON(needs.scan_project.outputs.stacks) }}
    steps:
      - name:  Preview Stack
        run: |
          # Would run Pulumi up here
          echo ${{ matrix.stacks }}
