name: ci-merge
on: 
  push:
    branches:
    - main
jobs:
  scan_project:
    runs-on: ubuntu-latest
    outputs:
      stacks: ${{ steps.publish.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: |
            pulumi/project_config/*/Pulumi.*.yaml
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Generate stack list
        id: publish
        uses: actions/github-script@v6
        with:
          script: |
            changed_stacks = `${{steps.changed-files.outputs.all_changed_files}}`
            return changed_stacks.split(" ");

  # Run preview on each of the stacks (This spins up an individual job per stack)
  preview_stack:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - scan_project
    strategy:
      matrix:
        include:
          - stacks: "foo"
            environment: "production"
          - stacks: "bar"
            environment: "staging"
    steps:
      - name:  Preview Stack
        run: |
          # Would run Pulumi up here
          echo ${{ matrix.stacks }}
